<header class="header">
    <a href="index.php" class='title'><h1>Portfolio Dulompont</h1><p>Développeur Web</p></a>
    <nav>
        <a href="index.php">Accueil</a>
        <a href='about.php'>À propos</a>
        <a href="projets.php">Mes projets</a>
    </nav>
    <div>
        <a href="contact.php" class="contactBut current">Me contacter</a>
    </div>
</header>
    <main class="container">
            <form action="contact.php" method="POST" class="contactForm">
            <div class="card">
                <h2>Me contacter</h2>
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label>Nom</label>
                            <input type="text">
                        </div>
                    </div>

                    <div class="col">
                        <div class="form-group">
                            <label>Email</label>
                            <input type="text">
                        </div>
                    </div>

                    <div class="col">
                        <div class="form-group">
                            <label>Message</label>
                            <textarea></textarea>
                        </div>
                    </div>

                    <div class="col">
                        <input type="submit" value="Submit">
                    </div>
                </div>
                </div>
            </form>
    </main>
