<header class="header">
    <a href="index.php" class='title'><h1>Portfolio Dulompont</h1><p>Développeur Web</p></a>
    <nav>
        <a href="index.php">Accueil</a>
        <a href='about.php'>À propos</a>
        <a href="projets.php">Mes projets</a>
    </nav>
    <div>
        <a href="contact.php" class="contactBut current">Me contacter</a>
    </div>
</header>
    <main class="container">
        <section class="contactForm">
            <form action="contact.php" method="POST">
                <h2 class='contactTitle'>Formulaire de contact</h2>
                <p>Veuillez remplir ce formulaire si vous souhaitez me contacter.</p>
                <ul class='none'>
                    <li>
                        <label for='name'>Nom :</label>
                        <input type="text" name="name" id="name" required>
                    </li>
                    <li>
                        <label for='email'>Email :</label>
                        <input type="email" name="email" id ="email" required>
                    </li>
                    <li>
                        <label for='subject'>Sujet :</label>
                        <select name='subject' id='subject'>
                            <?php foreach($subjects as $subject): ?>
                                <option value=<?= $subject['id'] ?>><?= $subject['subject'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </li>
                    <li>
                        <label for='message'>Message :</label><br>
                    </li>
                    <li>
                        <textarea rows='10' cols='30' name="message" id="message"></textarea>
                    </li>
                    <li>
                        <button type='submit' class='send'>Envoyer le message</button>
                    </li>
                </ul>     
            </form>
        </section>
    </main>
