<header class="header">
    <a href="index.php" class='title'><h1>Portfolio</h1></a>
    <nav>
        <a href="index.php" class="current">Accueil</a>
        <a href='about.php'>À propos</a>
        <a href="projets.php">Mes projets</a>
    </nav>
    <div>
        <a href="contact.php" class="contactBut">Me contacter</a>
    </div>
</header>
<main class="container">
    <section class="intro">
        <article>
            <figure class='logos'>
                <img src="img/logos.png" alt="logos utilisés">
                <figcaption>Les langages que j'utilise</figcaption>
            </figure>
            <h2>Pourquoi ce portfolio?</h2>
            <p>Ce présent portfolio a pour vocation d'être une vitrine de mes capacités de développeur web. Il regroupe différents projets, chacun avec ses spécificités.</p>
            <p>Certains de mes projets sont plus axés front, d'autres plus axés back. Si vous recherchez un apprenti en back, je vous invite à vous concentrer sur les projets contenant du back et inversement.</p>
            <p>Dans un souci d'authenticité, j'ai réalisé ce site web sans utiliser de librairie ou de framework. Ainsi, vous pouvez observer mes capacités actuelles avec les langages ci-contre.</p>
        </article>
    </section>
    <section class="aboutMe">
        <article id="who">
            <figure class='me'>
                <img src="img/moi.jpg" alt="Photo de moi">
            </figure>
            <h3>Qui suis-je?</h3>
            <p>Je m'appelle Valentin Dulompont, j'ai 22 ans, et je suis un futur apprenti Développeur FullStack.</p>
            <p>Après plusieurs années à travailler divers langages en autodidacte, ou à l'université, j'ai décidé d'intégrer la formation Développeur Web auprès de la 3WAcademy.<br>
            J'ai donc postulé pour tenter le <a href="https://www.3wrh.fr/" target="_blank">Concours qui casse les codes de la 3WRH</a>
            Après avoir passé des tests de logique et réalisé le "mois zéro" en une semaine, j'ai débuté la véritable formation le 21 Juin 2021.</p>
            <p>La formation initiale étant finie depuis le 8 Septembre 2021, je souhaite intégrer une entreprise en tant qu'apprenti pour réaliser la formation Développeur FullStack en alternance.</p>
        </article>
    </section>
    
</main>
