<header class="header">
    <a href="index.php" class='title'><h1>Portfolio</h1></a>
    <nav>
        <a href="index.php" class="current">Accueil</a>
        <a href='about.php'>À propos</a>
        <a href="projets.php">Mes projets</a>
        <a href='contact.php'>Me contacter</a>
    </nav>
</header>
<main>
    <section class="intro">
        <article>
            <h2>Pourquoi ce portfolio?</h2>
            <p>Ce présent portfolio a pour vocation d'être une vitrine de mes capacités de développeur web. Il regroupe différents projets, chacun avec ses spécificités.</p>
            <p>Certains de mes projets sont plus axés front, d'autres plus axés back. Si vous recherchez un apprenti en back, je vous invite à vous concentrer sur les projets contenant du back et inversement.</p>
        </article>
        
    </section>
    <section class="aboutMe">
        <article id="who">
            <h3>Qui suis-je?</h3>
            <p>Je suis un jeune étudiant de 22 ans en développement Web à la recherche d'une alternance.</p>
            <p>Après plusieurs années à travailler divers langages en autodidacte, ou à l'université, j'ai décidé d'intégrer la formation Développeur Web auprès de la 3WAcademy.<br>
            J'ai donc postulé pour tenter le <a href="https://www.3wrh.fr/" target="_blank">Concours qui casse les codes de la 3WRH</a>
            Après avoir passé des tests de logique et ai réalisé le "mois zéro" en une semaine, pour débuter la véritable formation le 21 Juin 2021.</p>
            <p>La formation initiale se terminant en Septembre 2021, je souhaite intégrer une entreprise en tant qu'apprenti pour réaliser la formation Développeur FullStack en alternance.</p>
        </article>
    </section>
    
    </section>
    
</main>
