<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="./style.css" rel="stylesheet">
    <title>Portfolio</title>
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet"> 
</head>
<body>

    <?php require $template . '.phtml'; ?>
    
    <footer>
        <p>Réalisé par Valentin Dulompont. Avec le soutien de la <a href="https://3wa.fr" target="_blank">3WAcademy</a></p>
        <section class="contact">
            <a href="https://github.com/OpexBurner1" target="_blank"><i class="fab fa-github-square fa-3x"></i></a>
            <a href="https://linkedin.com/in/valentin-dulompont-17978a216" target="_blank"><i class="fab fa-linkedin fa-3x"></i></a>
            <a href="contact.php"><i class="far fa-envelope fa-3x"></i></a>
        </section>
    </footer>
    
    <!-- scripts -->
    <script src="js/scripts.js"></script>
</body>
</html>