<header class="header">
    <a href="index.php" class='title'><h1>Portfolio</h1></a>
    <nav>
        <a href="index.php">Sommaire</a>
        <a href='about.php'>À propos</a>
        <a href="projets.php" class="current">Mes projets</a>
        <a href='contact.php'>Me contacter</a>
    </nav>
</header>
<main>
    <section class="projets">
        <?php foreach($articles as $article): ?>
            <article>
                <a href="<?= $article['url'] ?>" target="_blank">
                    <h3><?= $article['name'] ?></h3>
                    <img src="<?= $article['img_url'] ?>" alt="aperçu du projet <?= $article['name'] ?>">
                    <p><?= $article['description'] ?></p>
                </a>
            </article>
            
        <?php endforeach; ?>
    </section>
</main>