<header class="header">
    <a href="index.php" class='title'><h1>Portfolio Dulompont</h1><p>Développeur Web</p></a>
    <nav>
        <a href="index.php">Accueil</a>
        <a href='about.php'>À propos</a>
        <a href="projets.php" class="current">Mes projets</a>
    </nav>
    <div>
        <a href="contact.php" class="contactBut">Me contacter</a>
    </div>
</header>
<main>
    <section class="projets">
        <?php foreach($articles as $article): ?>
            <article>
                <h2><?= $article['name'] ?></h2>
                <figure>
                    <img src="<?= $article['img_url'] ?>" alt="aperçu du projet <?= $article['name'] ?>">
                    <figcaption class="hiddenButton">
                        <a href="<?= $article['url'] ?>" target='_blank'>Ouvrir le projet</a>
                    </figcaption>
                </figure>
                <p><?= $article['description'] ?></p>
            </article>
            
        <?php endforeach; ?>
    </section>
</main>