<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>PHP</title>
    <link rel="stylesheet" href="order-form.css">
</head>
<body>
    <section>
        <h1>Bons de commande</h1>

        <a href="index.php">Retourner à l'accueil</a>

        <!-- Etiquette avec fiche client -->
        <article class="order-form-customer">
            <h2></h2>
            <h3></h3>
            <p></p>
            <p></p>
            <p></p>
        </article>
        <hr>

        <!-- Le bon de commande -->
        <table class="standard-table">
            <caption>Bon de commande n° </caption>
            <thead>
                <tr>
                    <th>Produit</th>
                    <th class="money-column">Prix Unitaire</th>
                    <th>Quantité</th>
                    <th class="money-column">Prix Total</th>
                </tr>
            </thead>
            <!-- Un footer de tableau HTML se positionne AVANT le body ! -->
            <tfoot>
                <tr>
                    <th colspan="3">Montant Total HT</th>
                    <th> €</th>
                </tr>
                <tr>
                    <th colspan="3">TVA (20 %)</th>
                    <th> €</th>
                </tr>
                <tr>
                    <th colspan="3">Montant Total TTC</th>
                    
                    <th> €</th>
                </tr>
            </tfoot>
            <tbody>
                <?php foreach($order as $detail): ?>
                    <tr>
                        <td><?= $detail['productName'] ?></td>
                        <td class="money-column"><?= $detail['priceEach'] ?>€</td>
                        <td><?= $detail['quantityOrdered'] ?></td>
                        <td class="money-column"><?= $detail['priceEach']*$detail['quantityOrdered']?> €</td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>
</body>
</html>