<h2><i class="fa fa-cogs"></i> Panneau d'administration</h2>

<nav>
    <a href="add_post.php">Rédiger un nouvel article</a>
</nav>

<table>
    <caption>Liste des articles</caption>
    <thead>
        <tr>
            <th>Titre</th>
            <th>Article</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <!-- Affichage de tous les articles -->
        <?php foreach($articles as $article): ?>
            <tr>
                <td><a href="show_post.php?number=<?= $article['number'] ?>" target="_blank"><?= $article['title'] ?></a></td>
                <td><?= $article['content'] ?></td>
                <td><?= $article['firstName'] . $article['lastName'] ?></td>
                <td><?= $article['category'] ?></td>
                <td>
                    <a class="edit" href="edit_post.php?number=<?= $article['number'] ?>"><i class="fa fa-pencil"></i></a>
                    <a class="remove" href="delete_post.php?number=<?= $article['number'] ?>"><i class="fa fa-remove"></i></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>