<h2><i class="fas fa-sign-in-alt"></i> Se connecter</h2>

<form class="generic-form" action="login.php" method="POST">
    <ul>
        <li>
            <label for="username">Nom d'utilisateur</label>
            <input type="text" name="username">
        </li>
        <li>
            <label for="password">Mot de passe</label>
            <input type="password" name="password">
        </li>
        <li>
            <button class="button button-primary" type="submit">Se connecter</button>
        </li>
    </ul>
</form>